name: Lychee Link Checker

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight to catch rotting links

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --cache
            --max-cache-age 1d
            --no-progress
            --exclude-mail
            --exclude "linkedin.com"
            --exclude "twitter.com"
            "content/**/*.md" "layouts/**/*.html"
          fail: true
